#include "baseRT_tick.h"
#include <stddef.h>

typedef struct {
    const char *name;
    uint64_t value;
} ProbeEntry;

#define SZ(T) {"sizeof(" #T ")", sizeof(T)}
#define OFF(T, f)                                                                                                      \
    {"offsetof(" #T "," #f ")", offsetof(T, f)}, {                                                                     \
        "fieldsize(" #T "," #f ")", sizeof(((T *)0)->f)                                                                \
    }
#define CONST(N) {"const(" #N ")", (uint64_t)(int64_t)(N)}

static const ProbeEntry entries[] = {
    SZ(BaseRTArray),
    OFF(BaseRTArray, data),
    OFF(BaseRTArray, count),
    OFF(BaseRTArray, elem_size),

    SZ(BaseRTTokenRef),
    OFF(BaseRTTokenRef, ring_id),
    OFF(BaseRTTokenRef, index),
    OFF(BaseRTTokenRef, count),
    OFF(BaseRTTokenRef, _pad0),
    OFF(BaseRTTokenRef, generation),

    SZ(BaseRTRingRef),
    OFF(BaseRTRingRef, ring_id),
    OFF(BaseRTRingRef, index),
    OFF(BaseRTRingRef, generation),

    SZ(BaseRTBuf),
    OFF(BaseRTBuf, ptr),
    OFF(BaseRTBuf, len),

    SZ(BaseRTTokenRange),
    OFF(BaseRTTokenRange, start),
    OFF(BaseRTTokenRange, end),

    SZ(BaseRTSamplingParams),
    OFF(BaseRTSamplingParams, temperature),
    OFF(BaseRTSamplingParams, top_p),
    OFF(BaseRTSamplingParams, min_p),
    OFF(BaseRTSamplingParams, top_k),
    OFF(BaseRTSamplingParams, freq_penalty),
    OFF(BaseRTSamplingParams, presence_penalty),
    OFF(BaseRTSamplingParams, repeat_penalty),
    OFF(BaseRTSamplingParams, flags),

    SZ(BaseRTShedPolicy),
    OFF(BaseRTShedPolicy, victim_lanes),
    OFF(BaseRTShedPolicy, evictable_cache_classes),
    OFF(BaseRTShedPolicy, protected_quota_bytes),
    OFF(BaseRTShedPolicy, max_evict_bytes),

    SZ(BaseRTLaneAdmit),
    OFF(BaseRTLaneAdmit, lane_tag),
    OFF(BaseRTLaneAdmit, prompt),
    OFF(BaseRTLaneAdmit, seed_handle),
    OFF(BaseRTLaneAdmit, sampling),
    OFF(BaseRTLaneAdmit, logit_bias_handle),
    OFF(BaseRTLaneAdmit, params),
    OFF(BaseRTLaneAdmit, rng_counter_base),
    OFF(BaseRTLaneAdmit, grammar_handle),
    OFF(BaseRTLaneAdmit, strategy_slot),
    OFF(BaseRTLaneAdmit, determinism_class),
    OFF(BaseRTLaneAdmit, minimum_exactness),
    OFF(BaseRTLaneAdmit, allow_approximate),
    OFF(BaseRTLaneAdmit, want_logprobs),
    OFF(BaseRTLaneAdmit, required_cert_id),
    OFF(BaseRTLaneAdmit, host_sampler_identity),
    OFF(BaseRTLaneAdmit, grammar_replay),
    OFF(BaseRTLaneAdmit, decode_replay),

    SZ(BaseRTLaneCommit),
    OFF(BaseRTLaneCommit, lane_tag),
    OFF(BaseRTLaneCommit, token_id),
    OFF(BaseRTLaneCommit, _pad0),
    OFF(BaseRTLaneCommit, logits_nonce),

    SZ(BaseRTLanePrefill),
    OFF(BaseRTLanePrefill, lane_tag),
    OFF(BaseRTLanePrefill, token_offset),
    OFF(BaseRTLanePrefill, token_count),

    SZ(BaseRTLaneDecode),
    OFF(BaseRTLaneDecode, lane_tag),
    OFF(BaseRTLaneDecode, max_new_tokens),
    OFF(BaseRTLaneDecode, overshoot),
    OFF(BaseRTLaneDecode, _pad1),

    SZ(BaseRTLaneRetire),
    OFF(BaseRTLaneRetire, lane_tag),
    OFF(BaseRTLaneRetire, publish_to_cache),
    OFF(BaseRTLaneRetire, _pad0),

    SZ(BaseRTTickPlan),
    OFF(BaseRTTickPlan, struct_size),
    OFF(BaseRTTickPlan, plan_seq),
    OFF(BaseRTTickPlan, flags),
    OFF(BaseRTTickPlan, _pad0),
    OFF(BaseRTTickPlan, prefill_token_budget),
    OFF(BaseRTTickPlan, max_decode_lanes),
    OFF(BaseRTTickPlan, admits),
    OFF(BaseRTTickPlan, commits),
    OFF(BaseRTTickPlan, prefills),
    OFF(BaseRTTickPlan, decodes),
    OFF(BaseRTTickPlan, retires),
    OFF(BaseRTTickPlan, shed_policy),
    OFF(BaseRTTickPlan, on_partial_emit),
    OFF(BaseRTTickPlan, partial_emit_user),

    SZ(BaseRTAdmitResult),
    OFF(BaseRTAdmitResult, lane_tag),
    OFF(BaseRTAdmitResult, status),
    OFF(BaseRTAdmitResult, reject_code),
    OFF(BaseRTAdmitResult, cert_id),
    OFF(BaseRTAdmitResult, granted_class),
    OFF(BaseRTAdmitResult, _pad0),

    SZ(BaseRTSpecStats),
    OFF(BaseRTSpecStats, proposed),
    OFF(BaseRTSpecStats, accepted),
    OFF(BaseRTSpecStats, cert_id_in_effect),
    OFF(BaseRTSpecStats, _pad0),

    SZ(BaseRTLaneEmit),
    OFF(BaseRTLaneEmit, lane_tag),
    OFF(BaseRTLaneEmit, token_ref),
    OFF(BaseRTLaneEmit, n_tokens),
    OFF(BaseRTLaneEmit, finish),
    OFF(BaseRTLaneEmit, logits_row),
    OFF(BaseRTLaneEmit, spec),
    SZ(BaseRTLaneLogprob),
    OFF(BaseRTLaneLogprob, lane_tag),
    OFF(BaseRTLaneLogprob, logprob),
    OFF(BaseRTLaneLogprob, n_top),
    OFF(BaseRTLaneLogprob, top_ids),
    OFF(BaseRTLaneLogprob, top_logprobs),

    SZ(BaseRTLaneFault),
    OFF(BaseRTLaneFault, lane_tag),
    OFF(BaseRTLaneFault, code),
    OFF(BaseRTLaneFault, _pad0),
    OFF(BaseRTLaneFault, detail),

    SZ(BaseRTShedEntry),
    OFF(BaseRTShedEntry, lane_tag),
    OFF(BaseRTShedEntry, kind),
    OFF(BaseRTShedEntry, reason),
    OFF(BaseRTShedEntry, bytes),
    OFF(BaseRTShedEntry, tokens),

    SZ(BaseRTShedReport),
    OFF(BaseRTShedReport, prefill_chunks_dropped),
    OFF(BaseRTShedReport, evictions_performed),
    OFF(BaseRTShedReport, bytes_evicted),
    OFF(BaseRTShedReport, entries),

    SZ(BaseRTOpComplete),
    OFF(BaseRTOpComplete, op),
    OFF(BaseRTOpComplete, state),
    OFF(BaseRTOpComplete, _pad0),
    OFF(BaseRTOpComplete, error),
    OFF(BaseRTOpComplete, bytes_moved),

    SZ(BaseRTTickTimings),
    OFF(BaseRTTickTimings, wall_ns),
    OFF(BaseRTTickTimings, prefill_ns),
    OFF(BaseRTTickTimings, decode_ns),
    OFF(BaseRTTickTimings, graph_hits),
    OFF(BaseRTTickTimings, graph_misses),

    SZ(BaseRTMemCounters),
    OFF(BaseRTMemCounters, allocated_bytes),
    OFF(BaseRTMemCounters, host_retained_bytes),
    OFF(BaseRTMemCounters, pool_blocks_total),
    OFF(BaseRTMemCounters, pool_blocks_used),
    OFF(BaseRTMemCounters, pool_bytes_evictable),
    OFF(BaseRTMemCounters, tentative_bytes),

    SZ(BaseRTTickEvents),
    OFF(BaseRTTickEvents, struct_size),
    OFF(BaseRTTickEvents, plan_seq),
    OFF(BaseRTTickEvents, tick_status),
    OFF(BaseRTTickEvents, _pad0),
    OFF(BaseRTTickEvents, admit_results),
    OFF(BaseRTTickEvents, emits),
    OFF(BaseRTTickEvents, faults),
    OFF(BaseRTTickEvents, shed),
    OFF(BaseRTTickEvents, op_completions),
    OFF(BaseRTTickEvents, timings),
    OFF(BaseRTTickEvents, mem),
    OFF(BaseRTTickEvents, logprobs),

    SZ(BaseRTStateSpaceDesc),
    OFF(BaseRTStateSpaceDesc, space_id),
    OFF(BaseRTStateSpaceDesc, kind),
    OFF(BaseRTStateSpaceDesc, version_tag),
    OFF(BaseRTStateSpaceDesc, bytes_per_token),
    OFF(BaseRTStateSpaceDesc, blob_bytes),
    OFF(BaseRTStateSpaceDesc, page_size_tokens),
    OFF(BaseRTStateSpaceDesc, fork_cost_class),
    OFF(BaseRTStateSpaceDesc, fork_cost_bytes),
    OFF(BaseRTStateSpaceDesc, snapshot_cadence),
    OFF(BaseRTStateSpaceDesc, snapshot_interval_tokens),
    OFF(BaseRTStateSpaceDesc, placement),
    OFF(BaseRTStateSpaceDesc, flags),
    OFF(BaseRTStateSpaceDesc, name),

    SZ(BaseRTArtifact),
    OFF(BaseRTArtifact, role),
    OFF(BaseRTArtifact, _pad0),
    OFF(BaseRTArtifact, content_hash),
    OFF(BaseRTArtifact, byte_size),
    OFF(BaseRTArtifact, load_path),

    SZ(BaseRTTapSpec),
    OFF(BaseRTTapSpec, layer),
    OFF(BaseRTTapSpec, tensor),
    OFF(BaseRTTapSpec, dtype),
    OFF(BaseRTTapSpec, layout),

    SZ(BaseRTCapabilityReq),
    OFF(BaseRTCapabilityReq, kind_id),
    OFF(BaseRTCapabilityReq, _pad0),
    OFF(BaseRTCapabilityReq, params),

    SZ(BaseRTStrategyRegistration),
    OFF(BaseRTStrategyRegistration, struct_size),
    OFF(BaseRTStrategyRegistration, strategy_id),
    OFF(BaseRTStrategyRegistration, impl_version),
    OFF(BaseRTStrategyRegistration, impl_hash),
    OFF(BaseRTStrategyRegistration, config_hash),
    OFF(BaseRTStrategyRegistration, artifacts),
    OFF(BaseRTStrategyRegistration, taps),
    OFF(BaseRTStrategyRegistration, capabilities),
    OFF(BaseRTStrategyRegistration, target_archs),
    OFF(BaseRTStrategyRegistration, kernel_caps_required),
    OFF(BaseRTStrategyRegistration, _pad0),
    OFF(BaseRTStrategyRegistration, est_state_bytes),
    OFF(BaseRTStrategyRegistration, claimed_exactness),
    OFF(BaseRTStrategyRegistration, _pad1),
    OFF(BaseRTStrategyRegistration, rng_contract_version),

    SZ(BaseRTExactnessCert),
    OFF(BaseRTExactnessCert, cert_id),
    OFF(BaseRTExactnessCert, exactness),
    OFF(BaseRTExactnessCert, sampling_modes),
    OFF(BaseRTExactnessCert, grammar_allowed),
    OFF(BaseRTExactnessCert, logit_bias_allowed),
    OFF(BaseRTExactnessCert, param_domain),
    OFF(BaseRTExactnessCert, verification_shape_class),
    OFF(BaseRTExactnessCert, admissible_host_identities),

    SZ(BaseRTStrategyGrant),
    OFF(BaseRTStrategyGrant, struct_size),
    OFF(BaseRTStrategyGrant, strategy_slot),
    OFF(BaseRTStrategyGrant, _pad0),
    OFF(BaseRTStrategyGrant, certificates),
    OFF(BaseRTStrategyGrant, state_spaces),
    OFF(BaseRTStrategyGrant, reserved_bytes),

    SZ(BaseRTOpStatus),
    OFF(BaseRTOpStatus, struct_size),
    OFF(BaseRTOpStatus, state),
    OFF(BaseRTOpStatus, _pad0),
    OFF(BaseRTOpStatus, error),
    OFF(BaseRTOpStatus, bytes_moved),

    SZ(BaseRTMatchCandidate),
    OFF(BaseRTMatchCandidate, prefix_len),
    OFF(BaseRTMatchCandidate, provenance_digest),
    OFF(BaseRTMatchCandidate, taint_bits),
    OFF(BaseRTMatchCandidate, resident_tier),
    OFF(BaseRTMatchCandidate, _pad0),

    SZ(BaseRTSpaceMatch),
    OFF(BaseRTSpaceMatch, space_id),
    OFF(BaseRTSpaceMatch, _pad0),
    OFF(BaseRTSpaceMatch, candidates),

    SZ(BaseRTMatchResult),
    OFF(BaseRTMatchResult, struct_size),
    OFF(BaseRTMatchResult, spaces),

    SZ(BaseRTStateEnvelope),
    OFF(BaseRTStateEnvelope, magic),
    OFF(BaseRTStateEnvelope, envelope_version),
    OFF(BaseRTStateEnvelope, space_kind),
    OFF(BaseRTStateEnvelope, compat_identity),
    OFF(BaseRTStateEnvelope, version_tag),
    OFF(BaseRTStateEnvelope, provenance_digest),
    OFF(BaseRTStateEnvelope, taint_bits),
    OFF(BaseRTStateEnvelope, _pad0),
    OFF(BaseRTStateEnvelope, range),
    OFF(BaseRTStateEnvelope, encoding),
    OFF(BaseRTStateEnvelope, _pad1),
    OFF(BaseRTStateEnvelope, checksum_kind),
    OFF(BaseRTStateEnvelope, payload_len),
    OFF(BaseRTStateEnvelope, content_checksum),

    SZ(BaseRTCacheKey),
    OFF(BaseRTCacheKey, compat_key),
    OFF(BaseRTCacheKey, provenance_digest),

    SZ(BaseRTRingDesc),
    OFF(BaseRTRingDesc, struct_size),
    OFF(BaseRTRingDesc, ring_id),
    OFF(BaseRTRingDesc, kind),
    OFF(BaseRTRingDesc, role),
    OFF(BaseRTRingDesc, slots),
    OFF(BaseRTRingDesc, slot_bytes),
    OFF(BaseRTRingDesc, _pad0),
    OFF(BaseRTRingDesc, base),
    OFF(BaseRTRingDesc, len),

    CONST(BASERT_STATUS_OK),
    CONST(BASERT_REJECT_BAD_STRIDE),
    CONST(BASERT_REJECT_BAD_ALIGNMENT),
    CONST(BASERT_REJECT_BOUNDS),
    CONST(BASERT_REJECT_BAD_REF_GENERATION),
    CONST(BASERT_REJECT_UNKNOWN_LANE),
    CONST(BASERT_REJECT_DUPLICATE_LANE),
    CONST(BASERT_REJECT_ILLEGAL_COMBINATION),
    CONST(BASERT_REJECT_BUDGET),
    CONST(BASERT_REJECT_STALE_SEED),
    CONST(BASERT_REJECT_HOST_RULES),
    CONST(BASERT_REJECT_TRANSFER_LOCKED),
    CONST(BASERT_REJECT_STALE_NONCE),
    CONST(BASERT_NEEDS_REPLAN),
    CONST(BASERT_REJECT_BAD_STRUCT),
    CONST(BASERT_EBUSY),
    CONST(BASERT_ERR_BUFFER_TOO_SMALL),
    CONST(BASERT_ERR_STALE_SIZING),
    CONST(BASERT_ERR_OUT_OF_BOUNDARY),
    CONST(BASERT_ERR_ENVELOPE_MISMATCH),
    CONST(BASERT_ERR_CHECKSUM),
    CONST(BASERT_ERR_IDENTITY_MISMATCH),
    CONST(BASERT_ERR_OP_UNSUPPORTED),
    CONST(BASERT_ERR_REGISTRATION_REFUSED),
    CONST(BASERT_ERR_UNKNOWN_HANDLE),
    CONST(BASERT_ERR_SEED_UNSERVABLE),
    CONST(BASERT_ERR_RING_LAYOUT),
    CONST(BASERT_REJECT_CERT_UNMATCHED),
    CONST(BASERT_ERR_FATAL),

    CONST(BASERT_FAULT_UNSPECIFIED),
    CONST(BASERT_FAULT_GRAMMAR_OVERFLOW),
    CONST(BASERT_FAULT_REF_SPAN_OOB),
    CONST(BASERT_FAULT_STRATEGY),
    CONST(BASERT_FAULT_OOM_TENTATIVE),
    CONST(BASERT_FAULT_INTERNAL),

    CONST(BASERT_SAMPLING_GPU_GREEDY),
    CONST(BASERT_SAMPLING_GPU_GUMBEL),
    CONST(BASERT_SAMPLING_HOST),
    CONST(BASERT_DETERMINISM_BEST_EFFORT),
    CONST(BASERT_DETERMINISM_DETERMINISTIC),
    CONST(BASERT_EXACTNESS_APPROXIMATE),
    CONST(BASERT_EXACTNESS_DISTRIBUTION_EXACT),
    CONST(BASERT_EXACTNESS_SEED_PATH_INVARIANT),
    CONST(BASERT_TICK_DRAIN),
    CONST(BASERT_TICK_CAPTURE_OK),
    CONST(BASERT_TICK_OK),
    CONST(BASERT_TICK_SHED),
    CONST(BASERT_TICK_LANE_ERRORS),
    CONST(BASERT_TICK_FATAL),
    CONST(BASERT_ADMIT_UNSPECIFIED),
    CONST(BASERT_ADMIT_ADMITTED),
    CONST(BASERT_ADMIT_REJECTED),
    CONST(BASERT_FINISH_NONE),
    CONST(BASERT_FINISH_EOS),
    CONST(BASERT_FINISH_LENGTH),
    CONST(BASERT_FINISH_GRAMMAR),
    CONST(BASERT_FINISH_CANCELLED),
    CONST(BASERT_FINISH_ERROR),
    CONST(BASERT_OP_PENDING),
    CONST(BASERT_OP_RUNNING),
    CONST(BASERT_OP_DONE),
    CONST(BASERT_OP_FAILED),
    CONST(BASERT_OP_CANCELLED),
    CONST(BASERT_ENCODING_LOSSLESS),
    CONST(BASERT_ENCODING_Q8),
    CONST(BASERT_ENCODING_Q4),
    CONST(BASERT_SPACE_KIND_UNSPECIFIED),
    CONST(BASERT_SPACE_KIND_PAGED_TOKEN_KV),
    CONST(BASERT_SPACE_KIND_RING_KV),
    CONST(BASERT_SPACE_KIND_RECURRENT_BLOB),
    CONST(BASERT_SPACE_KIND_DEPTH_PAGED_KV),
    CONST(BASERT_SPACE_KIND_ENCODER_CACHE),
    CONST(BASERT_ARTIFACT_UNSPECIFIED),
    CONST(BASERT_ARTIFACT_DRAFT_WEIGHTS),
    CONST(BASERT_ARTIFACT_AUX_HEAD),
    CONST(BASERT_ARTIFACT_PROJECTION),
    CONST(BASERT_ARTIFACT_DRAFT_TOKENIZER),
    CONST(BASERT_TAP_TENSOR_UNSPECIFIED),
    CONST(BASERT_TAP_TENSOR_HIDDEN),
    CONST(BASERT_TAP_TENSOR_ATTN_OUT),
    CONST(BASERT_TAP_TENSOR_EMBED),
    CONST(BASERT_CERT_MODE_GREEDY),
    CONST(BASERT_CERT_MODE_GUMBEL),
    CONST(BASERT_CERT_MODE_HOST),
    CONST(BASERT_CERT_DOMAIN_NONE),
    CONST(BASERT_CERT_DOMAIN_GREEDY_ONLY),
    CONST(BASERT_CERT_DOMAIN_PENALTY_FREE),
    CONST(BASERT_CERT_DOMAIN_ANY),
    CONST(BASERT_STRATEGY_CAP_UNSPECIFIED),
    CONST(BASERT_STRATEGY_CAP_PROPOSAL_LINEAR),
    CONST(BASERT_STRATEGY_CAP_PROPOSAL_BLOCK),
    CONST(BASERT_STRATEGY_CAP_PROPOSAL_TREE),
    CONST(BASERT_STRATEGY_CAP_MASK_ANCESTOR),
    CONST(BASERT_STRATEGY_CAP_HOST_COMPATIBLE),
    CONST(BASERT_TAINT_QUANTIZED_DEMOTION),
    CONST(BASERT_TAINT_DECOMPOSITION),
    CONST(BASERT_TIER_GPU),
    CONST(BASERT_TIER_HOST),
    CONST(BASERT_TIER_GONE),
    CONST(BASERT_SHED_UNSPECIFIED),
    CONST(BASERT_SHED_PREFILL_CHUNK),
    CONST(BASERT_SHED_CACHE_EVICTION),
    CONST(BASERT_FORK_EAGER),
    CONST(BASERT_CHECKSUM_XXH3_64),
    CONST(BASERT_CHECKSUM_FNV1A64),
    CONST(BASERT_ALL_SPACES),
    CONST(BASERT_STATE_ENVELOPE_MAGIC),
    CONST(BASERT_RING_MAGIC),
    CONST(BASERT_RING_KIND_UNSPECIFIED),
    CONST(BASERT_RING_KIND_TOKENS),
    CONST(BASERT_RING_KIND_LOGITS),
    CONST(BASERT_RING_ROLE_UNSPECIFIED),
    CONST(BASERT_RING_ROLE_ENGINE_READS),
    CONST(BASERT_RING_ROLE_ENGINE_WRITES),
};

uint64_t abi_probe_count(void) {
    return sizeof(entries) / sizeof(entries[0]);
}

const char *abi_probe_name(uint64_t i) {
    return entries[i].name;
}

uint64_t abi_probe_value(uint64_t i) {
    return entries[i].value;
}

#ifdef ABI_LAYOUT_PROBE_MAIN
#include <stdio.h>

int main(void) {
    for (uint64_t i = 0; i < abi_probe_count(); i++) {
        printf("%s\t%llu\n", entries[i].name, (unsigned long long)entries[i].value);
    }
    return 0;
}
#endif
